#!/usr/bin/env python
# encoding: utf-8

name = "harris_butane"
shortDesc = ""
longDesc = """

"""
autoGenerated=False
entry(
    index = 213,
    label = "C2H5(33) + HO2(16) <=> H2O2(17) + C2H4(11)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(100.07,'cm^3/(mol*s)'), n=3.43775, Ea=(48.6525,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.15458, dn = +|- 0.0188838, dEa = +|- 0.102765 kJ/mol"""),
)

entry(
    index = 390,
    label = "IC3H7(93) + CH2(23) <=> CH3(18) + C3H6(12)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(4.71002e+06,'cm^3/(mol*s)'), n=1.97886, Ea=(-5.44543,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.01023, dn = +|- 0.00133779, dEa = +|- 0.00728019 kJ/mol"""),
)

entry(
    index = 391,
    label = "NC3H7(92) + C2H3(22) <=> C2H4(11) + C3H6(12)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(8.94944,'cm^3/(mol*s)'), n=2.9381, Ea=(-24.3858,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.04036, dn = +|- 0.0051977, dEa = +|- 0.0282857 kJ/mol"""),
)

entry(
    index = 402,
    label = "SC4H9(183) + CH2(23) <=> CH3(18) + C4H8(188)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(13661.1,'cm^3/(mol*s)'), n=3.34686, Ea=(-31.5425,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.11841, dn = +|- 0.0147024, dEa = +|- 0.0800099 kJ/mol"""),
)

entry(
    index = 403,
    label = "NC3H7(92) + OH(15) <=> H2O(8) + C3H6(12)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(136099,'cm^3/(mol*s)'), n=2.75761, Ea=(-91.2191,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.13634, dn = +|- 0.0167919, dEa = +|- 0.0913809 kJ/mol"""),
)

entry(
    index = 411,
    label = "SC4H9(183) + CH3(18) <=> CH4(10) + C4H8(188)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(8185.26,'cm^3/(mol*s)'), n=2.80402, Ea=(-19.6142,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.06205, dn = +|- 0.0079095, dEa = +|- 0.0430432 kJ/mol"""),
)

entry(
    index = 418,
    label = "CH3CO(20) + HO2(16) <=> H2O2(17) + CH2CO(24)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(16748.4,'cm^3/(mol*s)'), n=2.99233, Ea=(-8.13211,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.00448, dn = +|- 0.000587019, dEa = +|- 0.00319454 kJ/mol"""),
)

entry(
    index = 419,
    label = "CH2CHO(21) + HO2(16) <=> H2O2(17) + CH2CO(24)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(555.362,'cm^3/(mol*s)'), n=3.11141, Ea=(1.61382,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.09712, dn = +|- 0.0121772, dEa = +|- 0.0662681 kJ/mol"""),
)

entry(
    index = 420,
    label = "SC4H9(183) + HO2(16) <=> H2O2(17) + C4H8(189)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(43.5589,'cm^3/(mol*s)'), n=3.3862, Ea=(33.1106,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.14679, dn = +|- 0.0179948, dEa = +|- 0.0979271 kJ/mol"""),
)

entry(
    index = 422,
    label = "SC4H9(183) + HO2(16) <=> H2O2(17) + C4H8(188)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(37.8134,'cm^3/(mol*s)'), n=3.43448, Ea=(49.7319,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.16396, dn = +|- 0.0199477, dEa = +|- 0.108554 kJ/mol"""),
)

entry(
    index = 427,
    label = "CH2CHO(21) + CH2CHO(21) <=> CH3CHO(35) + CH2CO(24)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(10665.5,'cm^3/(mol*s)'), n=2.77889, Ea=(-34.4429,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.02911, dn = +|- 0.00376994, dEa = +|- 0.0205159 kJ/mol"""),
)

entry(
    index = 433,
    label = "SC4H9(183) + HCO(19) <=> CH2O(9) + C4H8(188)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(172768,'cm^3/(mol*s)'), n=1.97207, Ea=(-1.50563,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.004, dn = +|- 0.000524594, dEa = +|- 0.00285482 kJ/mol"""),
)

entry(
    index = 438,
    label = "IC3H7(93) + CH2CHO(21) <=> CH3CHO(35) + C3H6(12)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(417.723,'cm^3/(mol*s)'), n=2.95473, Ea=(-8.51372,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.01885, dn = +|- 0.00245297, dEa = +|- 0.013349 kJ/mol"""),
)

entry(
    index = 445,
    label = "SC4H9(183) + CH3CO(20) <=> CH3CHO(35) + C4H8(188)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(394.205,'cm^3/(mol*s)'), n=2.95233, Ea=(-9.16249,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.014, dn = +|- 0.00182617, dEa = +|- 0.00993793 kJ/mol"""),
)

entry(
    index = 507,
    label = "C2H5(33) + NC3H7(92) <=> C2H6(32) + C3H6(12)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(1614.52,'cm^3/(mol*s)'), n=2.98011, Ea=(-7.39683,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.00808, dn = +|- 0.00105771, dEa = +|- 0.005756 kJ/mol"""),
)

entry(
    index = 574,
    label = "CH3O(31) + C3H5-A(94) <=> C3H6(12) + CH2O(9)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(6361.85,'cm^3/(mol*s)'), n=2.81045, Ea=(-9.14428,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.06111, dn = +|- 0.00779271, dEa = +|- 0.0424076 kJ/mol"""),
)

entry(
    index = 575,
    label = "C3H5-A(94) + NC3H7(92) <=> C3H6(12) + C3H6(12)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(2595.39,'cm^3/(mol*s)'), n=3.00006, Ea=(-8.08728,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.00341, dn = +|- 0.000447026, dEa = +|- 0.0024327 kJ/mol"""),
)

entry(
    index = 579,
    label = "SC4H9(183) + C3H5-A(94) <=> C3H6(12) + C4H8(188)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(17752.6,'cm^3/(mol*s)'), n=2.98271, Ea=(-2.04336,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.00286, dn = +|- 0.000375555, dEa = +|- 0.00204376 kJ/mol"""),
)

entry(
    index = 581,
    label = "C3H5-A(94) + CH2CHO(21) <=> C3H6(12) + CH2CO(24)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(97782.6,'cm^3/(mol*s)'), n=2.66551, Ea=(5.27917,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.05812, dn = +|- 0.00742271, dEa = +|- 0.0403941 kJ/mol"""),
)

entry(
    index = 669,
    label = "IC3H7(93) + C4H8(748) <=> SC4H9(183) + C3H6(12)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(96.7941,'cm^3/(mol*s)'), n=2.94878, Ea=(-10.5727,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.01327, dn = +|- 0.00173223, dEa = +|- 0.00942674 kJ/mol"""),
)

entry(
    index = 674,
    label = "SC4H9(183) + C4H8(748) <=> SC4H9(183) + C4H8(188)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(24.0418,'cm^3/(mol*s)'), n=2.97336, Ea=(-16.7809,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.00549, dn = +|- 0.000719294, dEa = +|- 0.00391437 kJ/mol"""),
)

entry(
    index = 720,
    label = "C4H7(190) + CH2CHO(21) <=> C4H8(189) + CH2CO(24)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(4083.22,'cm^3/(mol*s)'), n=2.68932, Ea=(-2.24194,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.05196, dn = +|- 0.0066555, dEa = +|- 0.036219 kJ/mol"""),
)

entry(
    index = 722,
    label = "C4H7(190) + CH2CHO(21) <=> C4H8(188) + CH2CO(24)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(63955.8,'cm^3/(mol*s)'), n=2.6777, Ea=(19.5204,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.05643, dn = +|- 0.00721276, dEa = +|- 0.0392516 kJ/mol"""),
)

entry(
    index = 725,
    label = "C4H7(190) + CH3O(31) <=> C4H8(189) + CH2O(9)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(150092,'cm^3/(mol*s)'), n=1.93096, Ea=(-8.85088,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.03226, dn = +|- 0.00417191, dEa = +|- 0.0227034 kJ/mol"""),
)

entry(
    index = 728,
    label = "C4H7(190) + SC4H9(183) <=> C4H8(188) + C4H8(189)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(96.486,'cm^3/(mol*s)'), n=2.97719, Ea=(-10.0104,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.01016, dn = +|- 0.00132772, dEa = +|- 0.0072254 kJ/mol"""),
)

entry(
    index = 731,
    label = "C4H7(190) + SC4H9(183) <=> C4H8(188) + C4H8(188)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(729.962,'cm^3/(mol*s)'), n=2.99612, Ea=(-7.14309,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.00947, dn = +|- 0.00123772, dEa = +|- 0.00673561 kJ/mol"""),
)

entry(
    index = 793,
    label = "C4H7(190) + HO2(16) <=> H2O2(17) + C4H6(194)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(80.1158,'cm^3/(mol*s)'), n=3.51961, Ea=(49.7108,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.18899, dn = +|- 0.0227424, dEa = +|- 0.123763 kJ/mol"""),
)

entry(
    index = 794,
    label = "C4H7(190) + CH3(18) <=> CH4(10) + C4H6(194)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(115772,'cm^3/(mol*s)'), n=2.98873, Ea=(-6.10652,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.01077, dn = +|- 0.00140801, dEa = +|- 0.00766232 kJ/mol"""),
)

entry(
    index = 795,
    label = "C4H7(190) + C4H7(190) <=> C4H8(189) + C4H6(194)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(75.9975,'cm^3/(mol*s)'), n=3.07709, Ea=(46.2691,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.0313, dn = +|- 0.0040492, dEa = +|- 0.0220356 kJ/mol"""),
)

entry(
    index = 798,
    label = "C4H7(190) + SC4H9(183) <=> butane(1) + C4H6(194)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(37.4759,'cm^3/(mol*s)'), n=2.98945, Ea=(-14.7395,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.00266, dn = +|- 0.000349281, dEa = +|- 0.00190077 kJ/mol"""),
)

entry(
    index = 802,
    label = "C4H7(190) + CH2CHO(21) <=> CH3CHO(35) + C4H6(194)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(2170.52,'cm^3/(mol*s)'), n=3.00456, Ea=(-8.45898,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.00469, dn = +|- 0.000615055, dEa = +|- 0.00334711 kJ/mol"""),
)

entry(
    index = 910,
    label = "C4H7(190) + CH2(23) <=> CH3(18) + C4H6(194)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(1496.89,'cm^3/(mol*s)'), n=3.39346, Ea=(-34.0906,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.12177, dn = +|- 0.0150961, dEa = +|- 0.0821522 kJ/mol"""),
)

entry(
    index = 915,
    label = "S(777) + O2(2) <=> HO2(16) + S(252)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(371.804,'cm^3/(mol*s)'), n=2.67859, Ea=(34.7911,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.06078, dn = +|- 0.00775211, dEa = +|- 0.0421867 kJ/mol"""),
)

entry(
    index = 984,
    label = "CH2CHO(21) + C4H8(748) <=> PC4H9(182) + CH2CO(24)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(3368.09,'cm^3/(mol*s)'), n=2.5889, Ea=(-36.2057,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.07499, dn = +|- 0.00949971, dEa = +|- 0.0516971 kJ/mol"""),
)

entry(
    index = 994,
    label = "C4H7(190) + C4H8(748) <=> PC4H9(182) + C4H6(194)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(2.32921,'cm^3/(mol*s)'), n=2.10129, Ea=(-21.7073,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.34765, dn = +|- 0.0391991, dEa = +|- 0.21332 kJ/mol"""),
)

entry(
    index = 1016,
    label = "SC4H9(183) + C4H7(191) <=> C4H8(188) + C4H8(188)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(1.73608,'cm^3/(mol*s)'), n=2.93731, Ea=(-15.2196,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.02472, dn = +|- 0.00320782, dEa = +|- 0.0174568 kJ/mol"""),
)

entry(
    index = 1063,
    label = "SC4H9(183) + C4H8(748) <=> butane(1) + C4H7(191)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(1.88635,'cm^3/(mol*s)'), n=2.93543, Ea=(-16.4642,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.0271, dn = +|- 0.00351265, dEa = +|- 0.0191157 kJ/mol"""),
)

entry(
    index = 1064,
    label = "PC4H9(182) + C4H8(748) <=> butane(1) + C4H7(191)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(20.6464,'cm^3/(mol*s)'), n=2.85852, Ea=(-6.63838,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.04039, dn = +|- 0.00520157, dEa = +|- 0.0283067 kJ/mol"""),
)

entry(
    index = 1103,
    label = "CH3O2(45) + CH2CHO(21) <=> CH3O2H(46) + CH2CO(24)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(473.002,'cm^3/(mol*s)'), n=3.12865, Ea=(6.42401,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.08656, dn = +|- 0.0109063, dEa = +|- 0.0593515 kJ/mol"""),
)

entry(
    index = 1108,
    label = "CH3O2(45) + C2H4O(703) <=> CH3O2H(46) + CH2CHO(21)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(1241.75,'cm^3/(mol*s)'), n=3.00696, Ea=(-13.242,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.00148, dn = +|- 0.000194178, dEa = +|- 0.00105671 kJ/mol"""),
)

entry(
    index = 1114,
    label = "CH3O2(45) + SC4H9(183) <=> CH3O2H(46) + C4H8(189)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(19.6143,'cm^3/(mol*s)'), n=3.40999, Ea=(40.5927,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.14543, dn = +|- 0.0178392, dEa = +|- 0.0970802 kJ/mol"""),
)

entry(
    index = 1191,
    label = "C4H7(190) + C4H7(192) <=> C4H8(188) + C4H6(194)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(166.502,'cm^3/(mol*s)'), n=2.99554, Ea=(-12.3943,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.0072, dn = +|- 0.000941923, dEa = +|- 0.00512591 kJ/mol"""),
)

entry(
    index = 1214,
    label = "C3H5O(129) + CH2(23) <=> CH3(18) + C3H4O(74)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(69.0291,'cm^3/(mol*s)'), n=4.10425, Ea=(-112.561,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.05023, dn = +|- 0.00643945, dEa = +|- 0.0350433 kJ/mol"""),
)

entry(
    index = 1252,
    label = "C4H8(748) + HCO(19) <=> CH2O(9) + C4H7(191)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(5716.27,'cm^3/(mol*s)'), n=2.95155, Ea=(-2.5295,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.01364, dn = +|- 0.0017796, dEa = +|- 0.00968449 kJ/mol"""),
)

entry(
    index = 1254,
    label = "C4H7(191) + C4H8(748) <=> C4H8(188) + C4H7(191)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(0.300374,'cm^3/(mol*s)'), n=2.3405, Ea=(-95.4931,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.25334, dn = +|- 0.029667, dEa = +|- 0.161447 kJ/mol"""),
)

entry(
    index = 1258,
    label = "CH3CO(20) + C4H8(748) <=> CH3CHO(35) + C4H7(191)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(1.69967,'cm^3/(mol*s)'), n=2.45641, Ea=(8.86997,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.24211, dn = +|- 0.0284846, dEa = +|- 0.155012 kJ/mol"""),
)

entry(
    index = 1328,
    label = "C3H5O3(72) + CH3O(31) <=> C3H6O3(73) + CH2O(9)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(2.10728,'cm^3/(mol*s)'), n=3.28624, Ea=(-33.3315,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.16909, dn = +|- 0.0205246, dEa = +|- 0.111694 kJ/mol"""),
)

entry(
    index = 1342,
    label = "C3H5O3(72) + C2H5(33) <=> C3H6O3(73) + C2H4(11)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(6.05279,'cm^3/(mol*s)'), n=2.75866, Ea=(37.7878,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.08984, dn = +|- 0.0113027, dEa = +|- 0.0615091 kJ/mol"""),
)

entry(
    index = 1350,
    label = "C3H5O3(72) + PC4H9(182) <=> C3H6O3(73) + C4H8(188)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(0.218687,'cm^3/(mol*s)'), n=2.6595, Ea=(21.3891,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.13222, dn = +|- 0.0163146, dEa = +|- 0.0887835 kJ/mol"""),
)

entry(
    index = 1369,
    label = "IC3H7(93) + C4H6(2534) <=> C4H7(190) + C3H6(12)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(535.385,'cm^3/(mol*s)'), n=3.0072, Ea=(-6.72285,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.00267, dn = +|- 0.000349663, dEa = +|- 0.00190285 kJ/mol"""),
)

entry(
    index = 1372,
    label = "SC4H9(183) + C4H6(2534) <=> C4H7(190) + C4H8(188)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(76.4061,'cm^3/(mol*s)'), n=2.90981, Ea=(-13.7371,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.02581, dn = +|- 0.00334807, dEa = +|- 0.0182201 kJ/mol"""),
)

entry(
    index = 1398,
    label = "C4H7(190) + C4H6(2534) <=> C4H7(190) + C4H6(194)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(334.495,'cm^3/(mol*s)'), n=2.96941, Ea=(-10.1162,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.01568, dn = +|- 0.00204363, dEa = +|- 0.0111213 kJ/mol"""),
)

entry(
    index = 1402,
    label = "IC3H7(93) + C4H6(2534) <=> C4H7(191) + C3H6(12)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(171.518,'cm^3/(mol*s)'), n=2.96236, Ea=(-11.7918,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.02068, dn = +|- 0.00268961, dEa = +|- 0.0146368 kJ/mol"""),
)

entry(
    index = 1410,
    label = "SC4H9(183) + C4H6(2534) <=> C4H7(191) + C4H8(188)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(17.0147,'cm^3/(mol*s)'), n=2.98178, Ea=(-15.3528,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.01271, dn = +|- 0.00165933, dEa = +|- 0.00903004 kJ/mol"""),
)

entry(
    index = 1529,
    label = "C2H5O(49) + CH3O(31) <=> CH3OH(30) + CH3CHO(35)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(17.7348,'cm^3/(mol*s)'), n=3.6443, Ea=(-56.7814,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.03429, dn = +|- 0.00442995, dEa = +|- 0.0241076 kJ/mol"""),
)

entry(
    index = 1625,
    label = "C4H8(748) + CH3(18) <=> CH4(10) + C4H7(191)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(43099.3,'cm^3/(mol*s)'), n=2.82821, Ea=(-19.4132,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.05453, dn = +|- 0.00697622, dEa = +|- 0.0379643 kJ/mol"""),
)

entry(
    index = 1658,
    label = "C2H5O2(47) + CH2CHO(21) <=> C2H6O2(48) + CH2CO(24)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(70.5869,'cm^3/(mol*s)'), n=3.20438, Ea=(6.02521,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.12041, dn = +|- 0.0149376, dEa = +|- 0.0812896 kJ/mol"""),
)

entry(
    index = 1665,
    label = "C2H5O2(47) + CH3O(31) <=> C2H6O2(48) + CH2O(9)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(31312.8,'cm^3/(mol*s)'), n=1.99076, Ea=(-16.919,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.0034, dn = +|- 0.000445573, dEa = +|- 0.00242479 kJ/mol"""),
)

entry(
    index = 1685,
    label = "C2H5O2(47) + C2H5(33) <=> C2H6O2(48) + C2H4(11)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(4.71517,'cm^3/(mol*s)'), n=3.47169, Ea=(54.5885,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.1501, dn = +|- 0.0183736, dEa = +|- 0.0999886 kJ/mol"""),
)

entry(
    index = 1688,
    label = "C2H5O2(47) + SC4H9(183) <=> C2H6O2(48) + C4H8(189)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(14.7923,'cm^3/(mol*s)'), n=2.95159, Ea=(-11.5144,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.01227, dn = +|- 0.0016025, dEa = +|- 0.00872075 kJ/mol"""),
)

entry(
    index = 1692,
    label = "C2H5O2(47) + C2H5O(49) <=> C2H6O2(48) + CH3CHO(35)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(1.19405,'cm^3/(mol*s)'), n=3.85287, Ea=(-9.23428,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.05468, dn = +|- 0.00699439, dEa = +|- 0.0380632 kJ/mol"""),
)

entry(
    index = 1721,
    label = "S(186) + CH2CHO(21) <=> S(187) + CH2CO(24)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(10.6018,'cm^3/(mol*s)'), n=3.06568, Ea=(-242.741,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.00991, dn = +|- 0.00129504, dEa = +|- 0.00704753 kJ/mol"""),
)

entry(
    index = 1736,
    label = "S(186) + CH3O(31) <=> S(187) + CH2O(9)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(815.523,'cm^3/(mol*s)'), n=2.84763, Ea=(-13.1822,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.04712, dn = +|- 0.00604906, dEa = +|- 0.0329188 kJ/mol"""),
)

entry(
    index = 1814,
    label = "S(5425) + O2(2) <=> HO2(16) + S(5951)",
    degeneracy = 1.0,
    elementary_high_p = True,
    kinetics = Arrhenius(A=(4.76242e+06,'cm^3/(mol*s)'), n=2.49162, Ea=(-3.2248,'kJ/mol'), T0=(1,'K'), Tmin=(298,'K'), Tmax=(2500,'K'), comment="""Fitted to 50 data points; dA = *|/ 1.00247, dn = +|- 0.00032449, dEa = +|- 0.00176586 kJ/mol"""),
)

